config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books do
  collection do
    get 'events', to: 'books#events'
  end
 end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :year,     presence: true
  validates :month,    presence: true
  validates :day,      presence: true
  validates :inout,    presence: true
  validates :category, presence: true
  validates :amount,   presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    book_params = params.require(:book).permit(:year, :month, :day, :inout, :category, :amount)
    @book = Book.new(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to books_path, notice: '家計簿が更新されました。'
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  def events
    @books = Book.all

    events = @books.map do |book|
      {
        title: "#{book.category} - #{book.amount}円",
        start: Date.new(book.year, book.month, book.day),
        url: book_path(book)
      }
    end

    render json: events
  end

  private

  def book_params
    params.require(:book).permit(:year, :month, :day, :inout, :category, :amount)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/edit.html.erb
<h1>家計簿更新</h1>

<%= form_with model:@book, local:true, method: "patch" do|f|%>
<div class = "form-group"><label>年度</label>
<%= f.number_field :year, class: "form-control"%></div>
<div class = "form-group"><label>月</label>
<%= f.number_field :month, class: "form-control"%></div>
<div class = "form-group"><label>日</label>
<%= f.number_field :day, class: "form-control"%></div>
<div class = "form-group"><label>区分</label>
<%= f.select :inout, [["夫精算",1],["妻精算",2],["精算完了",3]],{},{class:"form-control"}%></div>
<div class = "formgroup"><label>科目</label>
<%= f.text_field :category, class: "form-control"%></div>
<div class = "form-group"><label>金額</label>
<%= f.number_field :amount, class: "form-control"%></div>
<%= link_to "戻る",books_path,class: "btn btn-secondary" %>
<%= f.submit "更新", class: "btn-btnprimary" %>
<% end %>

 

app/views/books/index.html.erb
<h1>新米夫婦のための家計簿</h1>
<%= link_to "新規登録", new_book_path, class: "btn btn-success" %>

<div id="calendar" data-turbolinks-permanent></div>

<%= javascript_pack_tag 'calendar' %>

app/views/books/new.html.erb
<h1>家計簿新規登録</h1>
<%=form_with(model:@book,local:true) do |f|%>
<div class="form-group"><label>年</label>
<%=f.number_field:year,class:"form-control"%>
</div>
<div class="form-group"><label>月</label>
<%=f.number_field:month,class:"form-control"%></div>
<div class="form-group"><label>日</label>
<%=f.number_field:day,class:"form-control"%></div>
<div class="form-group"><label>区分</label>
<%=f.select:inout,[["夫支払い",1],["妻支払い",2],["精算完了",3]],{},{class:"form-control"}%></div>
<div class="form-group"><label>科目</label>
<%=f.text_field:category,class:"form-control"%></div>
<div class="form-group"><label>金額</label>
<%=f.number_field:amount,class:"form-control"%></div>
<%= link_to "戻る",books_path,class: "btn btn-secondary" %>
<%=f.submit "登録",class: "btn btn-primary"%>
<%end%>

app/views/books/show.html.erb
<h1>詳細情報</h1>

<table class="table table-striped">

<tr>
<th>年月</th>
<td>
<%= @book.year %>年<%= @book.month%>月</td>
</tr>
<tr>
<th>区分</th><td><%=@book.inout%></td>
</tr>
<tr>
<th>科目</th><td><%=@book.category%></td>
</tr>
<tr>
<th>金額</th><td><%=@book.amount%>円</td>
</tr>
</table>
<%= link_to "編集", edit_book_path(@book), class: "btn btn-warning" %>
<%= link_to "削除", book_path(@book), method: :delete, data: { confirm: '本当に削除しますか？' }, class: "btn btn-danger" %>
<%= link_to "戻る", books_path, class: "btn btn-secondary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kakeibo38872</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <script src="https://code.jquery.com/jquery3.5.1.slim.min.js"integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.1/js/bootstrap.min.js"integrity="sha384-XEerZL0cuoUbHE4nZReLT7nx9gQrQreJekYhJD9WNWhH8nEW+0c5qq7aIo2Wl30J"crossorigin="anonymous"></script>
  </body>
</html>